### PR TITLE
initial commit. add writingDate feature

### PR DESCRIPTION
**Pull request by night-hawks-wake**
첫 PR입니다. 확인해주세요~!

### CODE REVIEW

**Review by kkerast — COMMENTED** [review]
ok

**Comment by Bbarabarabam** [comment]
ok

**Comment by kkerast** [comment]
ok2

**Comment by kkerast** [comment]
ok3

**Comment by Bbarabarabam** [comment]
ok

**Comment by kkerast** [comment]
ok4

**Comment by Bbarabarabam** [comment]
ok

**Comment by kkerast** [comment]
ok5

**Comment by Bbarabarabam** [comment]
k

**Comment by night-hawks-wake** [comment]
......모르겠다

**Review by Bbarabarabam — COMMENTED** [review]
ok

**Review by Bbarabarabam — COMMENTED** [review]
ok

**Pull request closed without merging**
